// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD04wrKBMZkYgHHHXG-ium0ra5XJGMpClE',
    appId: '1:896104532490:web:dcf35362cad1c59712edf3',
    messagingSenderId: '896104532490',
    projectId: 'firestore-c72d0',
    authDomain: 'firestore-c72d0.firebaseapp.com',
    storageBucket: 'firestore-c72d0.firebasestorage.app',
    measurementId: 'G-9K6TG2WCE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Ldisd2e8y0wuvGEpF2M7mzuPChUk2_8',
    appId: '1:896104532490:android:993236f4567d9d8112edf3',
    messagingSenderId: '896104532490',
    projectId: 'firestore-c72d0',
    storageBucket: 'firestore-c72d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN44r7ErY8w0ejPAYN9uq6XIQNctoA2UU',
    appId: '1:896104532490:ios:f020cfee9dd81e2712edf3',
    messagingSenderId: '896104532490',
    projectId: 'firestore-c72d0',
    storageBucket: 'firestore-c72d0.firebasestorage.app',
    iosBundleId: 'com.example.tp4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN44r7ErY8w0ejPAYN9uq6XIQNctoA2UU',
    appId: '1:896104532490:ios:f020cfee9dd81e2712edf3',
    messagingSenderId: '896104532490',
    projectId: 'firestore-c72d0',
    storageBucket: 'firestore-c72d0.firebasestorage.app',
    iosBundleId: 'com.example.tp4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD04wrKBMZkYgHHHXG-ium0ra5XJGMpClE',
    appId: '1:896104532490:web:4ddbe5813906233d12edf3',
    messagingSenderId: '896104532490',
    projectId: 'firestore-c72d0',
    authDomain: 'firestore-c72d0.firebaseapp.com',
    storageBucket: 'firestore-c72d0.firebasestorage.app',
    measurementId: 'G-QVQPY2QLHT',
  );

}